package:
  name: bioconductor-biostrings
  version: 2.38.4
source:
  fn: r-bioc-biostrings_2.38.4.orig.tar.gz
  url: http://mirror2.tuxinator.org/ubuntu/pool/universe/r/r-bioc-biostrings/r-bioc-biostrings_2.38.4.orig.tar.gz
  md5: 1671ad0a1c200ed1dc23386bc53f1640
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - 'bioconductor-biocgenerics >=0.15.6'
    - 'bioconductor-iranges >=2.4.7'
    - 'bioconductor-s4vectors >=0.7.1'
    - 'bioconductor-xvector >=0.9.3'
    - r
  run:
    - 'bioconductor-biocgenerics >=0.15.6'
    - 'bioconductor-iranges >=2.4.7'
    - 'bioconductor-s4vectors >=0.7.1'
    - 'bioconductor-xvector >=0.9.3'
    - r
test:
  commands:
    - '$R -e "library(''Biostrings'')"'
about:
  home: http://bioconductor.org/packages/release/bioc/html/Biostrings.html
  license: Artistic-2.0
  summary: 'Memory efficient string containers, string matching algorithms, and other
    utilities, for fast manipulation of large biological sequences or sets of sequences.'
